### ISSUE TITLE
Questions regarding Asos extractor

### ISSUE THREAD

**Issue by se-jaeger** [calgo-lab/green-db#67]
Do we get only as sustainable tagged products from Asos? If yes, is it possible to add some code in the following snippet that uses `CertificateType.UNKNOWN` as label if we do not have any label mapping?

https://github.com/calgo-lab/green-db/blob/f255d8e6c5ff97dc555cf90e2f2bbec46b0a8092/extract/extract/extractors/asos.py#L160-L169

**Comment by BigDatalex** [comment]
Yes, all the products we are crawling are tagged as sustainable by Asos. We just had an offline discussion a while ago, where we decided to not use `CertificateType.UNKNOWN` for products where I have not identified a sensible sustainable phrasing/tagging. But if we want to change this now, we can just change the `else return` to return `[CertificateType.UNKNOWN]` instead of an empty list 😄

**Comment by se-jaeger** [comment]
I remember! Sorry!
